version: "3.3"

services:

  nginx-proxy:
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    build: ./nginx
    restart: unless-stopped
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-share:/usr/share/nginx/html
    networks:
      - auto-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  nginx-proxy-letsencrypt:
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    environment:
      DEFAULT_EMAIL: johannes.hinkov@gmail.com
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:rw
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-share:/usr/share/nginx/html

networks:
  auto-proxy:
    external: true

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-share:
